services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    container_name: django
    volumes:
      - ./backend:/loja_acai
      - ./staticfiles:/loja_acai/static  
    expose:
      - 8000  
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    container_name: nginx
    depends_on:
      - django
    volumes:
      - ./staticfiles:/usr/share/nginx/html/static  
    ports:
      - "80:80"  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
