services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    container_name: django
    volumes:
      - ./backend:/app
      - static_volume:/backend/loja_acai/static
      - ./backend/db.sqlite3:/app/db.sqlite3
    expose:
      - 8000  
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    container_name: nginx
    depends_on:
      - django
    volumes:
      - static_volume:/backend/loja_acai/static  # Arquivos estáticos
    ports:
      - "80:80"  # Expondo a porta 80 para o acesso público
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_volume: 
  db_data:
