services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    container_name: django
    environment:
      - DJANGO_DB_PATH=/data/db.sqlite3
    volumes:
      - ./backend:/app
      - static_volume:/backend/loja_acai/static
      - /home/ubuntu/data:/data
    expose:
      - 8000  
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    container_name: nginx
    depends_on:
      - django
    volumes:
      - static_volume:/backend/loja_acai/static
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_volume: 
