FROM python:3.9-alpine

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

COPY requirements.txt /code/requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /code

EXPOSE 8000

RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "--config", "gunicorn_config.py", "loja_acai.wsgi:application"]