# Generated by Django 4.2.16 on 2024-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_alter_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrescimos',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
