FROM nginx:alpine

RUN apk update && apk add --no-cache openssl

RUN mkdir -p /etc/ssl/certs /etc/ssl/private

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/privkey.pem -out /etc/ssl/certs/cert.pem -subj "/C=US/ST=State/L=City/O=Company/OU=Org/CN=localhost"

COPY nginx/nginx.conf /etc/nginx/nginx.conf

COPY backend/static /usr/share/nginx/html/static

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
